"""Generate a project's AGENTS.md.

The document is a human-readable brief for Claude Code that summarises the
project's known components, contracts, and data entities from the current
graph snapshot. Week-6 L1-L3 summaries flow in here as they become available.
"""

from __future__ import annotations

import uuid

from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.models.graph import Node
from app.models.projects import Project


async def build_agents_md(
    session: AsyncSession, *, project_id: uuid.UUID
) -> str:
    project = (
        await session.execute(select(Project).where(Project.id == project_id))
    ).scalar_one_or_none()
    if project is None:
        return "# AGENTS.md\n\n_project not found_\n"

    kind_counts = dict(
        (
            await session.execute(
                select(Node.kind, func.count())
                .where(Node.project_id == project_id, Node.valid_to.is_(None))
                .group_by(Node.kind)
            )
        ).all()
    )

    contracts = (
        await session.execute(
            select(Node)
            .where(
                Node.project_id == project_id,
                Node.kind == "Contract",
                Node.valid_to.is_(None),
            )
            .limit(100)
        )
    ).scalars().all()

    lines: list[str] = []
    lines.append(f"# AGENTS.md — {project.name}\n")
    lines.append(
        "This file is auto-generated by Mnemos. Update the platform, not this file.\n"
    )
    lines.append("## Quick facts\n")
    lines.append(f"- Languages: {', '.join(project.languages) or 'unknown'}")
    lines.append(f"- Default branch: `{project.default_branch}`")
    lines.append(f"- GitLab: {project.gitlab_url}")
    lines.append("")

    lines.append("## Graph snapshot\n")
    for kind, count in sorted(kind_counts.items()):
        lines.append(f"- **{kind}**: {count}")
    if not kind_counts:
        lines.append("- _no nodes yet — trigger analysis first_")
    lines.append("")

    if contracts:
        lines.append("## Known HTTP contracts\n")
        for c in contracts:
            data = c.data or {}
            spec = data.get("spec") or {}
            lines.append(
                f"- `{data.get('id', c.id)}` "
                f"({spec.get('method', '?')} {spec.get('path', '?')})"
            )
        lines.append("")

    lines.append("## Tooling\n")
    lines.append(
        "Claude Code receives the Mnemos MCP server via `.mcp.json`. Available "
        "query tools: `search_symbols`, `get_symbol`, `find_callers`, "
        "`find_callees`, `impact_analysis`, `get_contract`, `read_file`. Data "
        "and dev tools land in later weeks per spec §15."
    )
    lines.append("")
    return "\n".join(lines)
