"""Generate a project's AGENTS.md.

The document is an agent contract, not a narrative report. It tells Claude Code
or Codex how to query Mnemos before editing a large repository, while the full
graph stays in the Mnemos database.
"""

from __future__ import annotations

import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.artifacts.agent_context import build_project_index
from app.models.projects import Project


async def build_agents_md(
    session: AsyncSession, *, project_id: uuid.UUID
) -> str:
    project = (
        await session.execute(select(Project).where(Project.id == project_id))
    ).scalar_one_or_none()
    if project is None:
        return "# AGENTS.md\n\n_project not found_\n"

    index = await build_project_index(session, project_id=project_id, top_k=20)
    snapshot = index.get("analysis_snapshot", {})
    node_counts = snapshot.get("node_counts", {})
    edge_counts = snapshot.get("edge_counts", {})
    latest_run = snapshot.get("latest_run") or {}
    contracts = (index.get("entrypoints") or {}).get("contracts") or []
    hot_symbols = (index.get("entrypoints") or {}).get("hot_symbols") or []
    findings = (index.get("risk_queue") or {}).get("findings") or []

    lines: list[str] = []
    lines.append(f"# AGENTS.md — {project.name}\n")
    lines.append(
        "Auto-generated by Mnemos. Treat this as the project analysis contract; "
        "do not edit it by hand.\n"
    )
    lines.append("## Agent Contract\n")
    lines.append("- Mnemos graph is the source of truth; never infer facts that are not in graph evidence.")
    lines.append("- Never load the whole repository into context. Query Mnemos first, then read narrow file ranges only.")
    lines.append("- Preserve certainty: `verified` > `asserted` > `inferred`; never present inferred as verified.")
    lines.append("- Before editing a symbol, call `get_task_context_pack(target_id)` and `impact_analysis(symbol_id)`.")
    lines.append("- Before changing an API/contract, call `get_contract(contract_id)` and inspect callers/exposers.")
    lines.append("- Before changing DB logic, call `get_data_access(symbol_id)` and inspect each DataEntity touched.")
    lines.append("- If a response is truncated, narrow the query instead of asking for a larger dump.")
    lines.append("- Check `coverage_report` in `get_project_index` first: when status is `partial`/`insufficient`, the listed languages/paths are NOT in the graph — say so instead of guessing about them.")
    lines.append("")

    lines.append("## Project Snapshot\n")
    lines.append(f"- Languages: {', '.join(project.languages) or 'unknown'}")
    lines.append(f"- Default branch: `{project.default_branch}`")
    lines.append(f"- GitLab: {project.gitlab_url}")
    if latest_run:
        lines.append(
            f"- Latest analysis: `{latest_run.get('status')}` at "
            f"`{latest_run.get('completed_at') or latest_run.get('created_at')}` "
            f"for git `{latest_run.get('git_sha')}`"
        )
    lines.append("")

    coverage = index.get("coverage_report") or {}
    if coverage:
        lines.append("## Analysis Coverage\n")
        lines.append(f"- Status: `{coverage.get('status')}`")
        for gap in coverage.get("critical_gaps", []):
            lines.append(
                f"- ⚠ `{gap.get('language')}`: {gap.get('reason')} — "
                f"{gap.get('impact')}"
            )
        buckets = (coverage.get("graph_coverage") or {}).get(
            "symbols_by_top_dir", {}
        )
        if buckets:
            lines.append(
                "- Symbols by top dir: "
                + ", ".join(f"`{k}`={v}" for k, v in list(buckets.items())[:8])
            )
        lines.append("")

    lines.append("## Graph Inventory\n")
    if node_counts:
        lines.append("- Nodes: " + ", ".join(f"{k}={v}" for k, v in sorted(node_counts.items())))
    else:
        lines.append("- _no nodes yet — trigger analysis first_")
    if edge_counts:
        lines.append("- Edges: " + ", ".join(f"{k}={v}" for k, v in sorted(edge_counts.items())))
    lines.append("")

    if contracts:
        lines.append("## Entry Contracts (Top 20)\n")
        for c in contracts[:20]:
            data = c.get("data") or {}
            spec = data.get("spec") or data
            method = spec.get("method", "?")
            path = spec.get("path", data.get("path", "?"))
            lines.append(f"- `{c.get('id')}` `{method} {path}` certainty=`{c.get('certainty')}`")
        lines.append("")

    if hot_symbols:
        lines.append("## Hot Symbols (By Incoming Calls)\n")
        for sym in hot_symbols[:20]:
            lines.append(
                f"- `{sym.get('symbol_id')}` calls_in={sym.get('incoming_calls', 0)} "
                f"certainty=`{sym.get('certainty')}`"
            )
        lines.append("")

    if findings:
        lines.append("## Risk Queue (Top 20)\n")
        for finding in findings[:20]:
            subject = finding.get("subject_node_id") or finding.get("subject_edge_id") or "project"
            lines.append(
                f"- `{finding.get('id')}` kind=`{finding.get('kind')}` "
                f"risk={finding.get('risk_score')} subject=`{subject}`"
            )
        lines.append("")

    lines.append("## Required MCP Workflow\n")
    lines.append("1. Start with `get_project_index(top_k=25)` for orientation.")
    lines.append("2. Find a target with `search_symbols`, `list_findings`, or an ID from this file.")
    lines.append("3. Call `get_task_context_pack(target_id, intent)` before planning any edit.")
    lines.append("4. Use the pack's `next_mcp_queries` exactly; they are the bounded follow-up path.")
    lines.append("5. Read source only after the pack gives a file path or symbol location.")
    lines.append("6. For edits, submit a plan first, edit in the approved worktree, run tests, then submit diff.")
    lines.append("")
    lines.append("## Available Core Tools\n")
    lines.append(
        "`get_project_index`, `get_task_context_pack`, `search_symbols`, "
        "`get_symbol`, `find_callers`, `find_callees`, `impact_analysis`, "
        "`get_contract`, `get_data_access`, `get_data_entity`, "
        "`find_runtime_path`, `list_findings`, `read_file`, `submit_plan`, "
        "`edit_file_in_worktree`, `run_in_sandbox`, `submit_diff`."
    )
    lines.append("")
    return "\n".join(lines)
